# Generated by Django 5.2.6 on 2025-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('horario', models.CharField(default='9:00 - 18:00', max_length=50)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
